name: hotel_search
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
 
dependencies:
  flutter:
    sdk: flutter
  
  splashscreen: ^1.2.0
  flutter_spinkit: "^4.1.2"
  date_range_picker: ^1.0.5
  intl:
  numberpicker: ^1.2.1
  flutter_picker: ^1.1.5
  flutter_launcher_icons: "^0.8.0"
  simple_animations: ^1.3.3 
  page_transition: ^1.1.4 
  
  flutter_svg: ^0.18.0
  page_indicator: ^0.3.0
  rect_getter: 0.0.1
  modal_bottom_sheet: 0.2.2 
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^8.5.0 
  cloud_firestore: ^0.14.0 
  firebase_core : ^0.5.0
  percent_indicator: ^2.1.1
  cupertino_setting_control: ^1.0.0+7 
  hexcolor: ^1.0.4
  flip_card: ^0.4.4
  qr_flutter: ^3.2.0
  provider: ^4.3.2+2
  show_up_animation: ^1.0.4
  ripple_backdrop_animate_route: ^0.1.2
  secure_random: ^1.0.0
  flutter_dialogs: ^1.0.4
  twitter_qr_scanner: any
  geolocator: 6.0.0+1 
  url_launcher: ^5.7.2
  overlay_screen: ^1.2.0+1 
  animated_text_kit: ^2.2.0
  custom_navigation_bar: ^0.3.2
  fluttertoast: ^7.0.1
  flutter_statusbarcolor: ^0.2.3
  countdown_flutter: ^0.1.2
  shared_preferences: ^0.5.12+2
  flutter_phoenix: "^0.1.0"



 
















  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test: 
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is 
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets: 
    - assets/images/sunbird_splash.png
    - assets/images/sunbird-capital.jpg
    - assets/images/sunbird2.jpg
    - assets/images/mount_soche.jpg
    - assets/images/
    - assets/images/starter-image.jpg
    - assets/images/one.jpg
    - assets/images/two.jpg
    - assets/images/three.jpg
    - assets/images/brand.png
    - assets/images/sunbird_white.png
    - img/
    - assets/images/detail1.jpg
    - assets/images/detail2.jpg
    - assets/images/detail3.jpg
    - Assets/image1.png
    - Assets/image2.png
    - assets/images/
    - assets/icons/


    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
    - family:  HotelBookingConcept
      fonts:
        - asset: fonts/HotelBookingConcept.ttf
    - family: SFUIDisplay
      fonts:
        - asset: Assets/sf-ui-display-light.otf

    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_regular.otf
      
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
